[project]
name = 'Exoplanet-Terraforming-Simulator'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.exoplanet-management]
path = 'contracts/exoplanet-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.terraforming-strategy]
path = 'contracts/terraforming-strategy.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
